### ISSUE TITLE
簡易的なロゴ画像差し替え処理の実装

### ISSUE THREAD

**Issue by nakanek** [EC-CUBE/order-pdf-plugin#13]
こちらのプラグインですが、例えば

```
app/template/admin/OrderPdf/logo.png
```

にファイルが存在すればそのファイルを帳票に指定し、
なければデフォルトの動作とすることで、
プラグイン内に手を加えずにロゴ画像を変更することが出来るかと思いますが、
このような対応方法だと何か懸念事項（EC-CUBEの作法としてNGなど）はありますでしょうか？
（画像サイズが286×38pxでなければ表示が崩れてしまうのは認識しています）
特に問題なさそうであれば対応してプルリクを投げようかと思っています。

よろしくお願いします。

**Comment by Yangsin** [comment]
ご意見ありがとうございます。
以下のテンプレートの探査順序などと同様にしておければよさそうですね。
http://ec-cube.github.io/template.html

**Comment by nakanek** [comment]
ご回答ありがとうございます。
教えて頂いたURLを元にapp配下を優先して読み込むよう修正し、プルリクエストを作成してみました。
https://github.com/EC-CUBE/order-pdf-plugin/pull/14

**Comment by ryo-endo** [comment]
#14のPRにもコメントさせていただきましたが、1.0.0で取り込ませていただきました。
ご提案ありがとうございました。
