### ISSUE TITLE
Entityのネームスペースが間違えてます

### ISSUE THREAD

**Issue by trebla-on** [EC-CUBE/order-pdf-plugin#16]
ec-cube 3.0.12
プラグイン：OrderPdf 0.0.2

問題：yamlファイルの中にネームスペースが間違えてます
ファイル：app/Plugin/OrderPdf/Resource/doctrine/Plugin.OrderPdf.Entity.OrderPdfPlugin.dcm.yml 
対応方法：
行目：１
Plugin\OrderPdf\Entity\OrderpdfPlugin:
↓
Plugin\OrderPdf\Entity\OrderPdfPlugin:

**Comment by ryo-endo** [comment]
1.0.0で、Plugin.OrderPdf.Entity.OrderPdfPlugin.dcm.ymlファイル削除となりました。
CLOSEします。
