### ISSUE TITLE
YamlのEntity設定ファイルの中にテーブル名が間違えてます(OrderPdfOrderDetail.dcm.yml) 

### ISSUE THREAD

**Issue by trebla-on** [EC-CUBE/order-pdf-plugin#19]
ec-cube 3.0.12
プラグイン：OrderPdf 0.0.2

問題：YamlのEntity設定ファイルの中にテーブル名が間違えてます
ファイル： app/Plugin/OrderPdf/Resource/doctrine/Plugin.OrderPdf.Entity.OrderPdfOrderDetail.dcm.yml

対応方法：
行目：3
    table: dtb_order_detail

**Comment by ryo-endo** [comment]
1.0.0で、Plugin.OrderPdf.Entity.OrderPdfOrderDetail.dcm.ymlファイル削除となりました。
CLOSEします。
