### ISSUE TITLE
プラグインのファイルサイズが大きすぎて、環境によっては独自プラグインとしてインストールできない

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/order-pdf-plugin#9]
プラグインのファイルサイズが約16MBあるため、
サーバ環境によっては最大アップロードサイズを越えてしまい、インストールができません。

オーナーズストアからのインストールは問題なし。

**Comment by ryo-endo** [comment]
html/.htaccessに下記記載をすることで、最大アップロードサイズを増やして回避可能。

```
php_value upload_max_filesize 20M
php_value post_max_size 20M
```

**Comment by ryo-endo** [comment]
ref #4

**Comment by yosshieee** [comment]
メモリの上限をあげることについては、readmeに書いておいた方が良いのではないでしょうか？

**Comment by yosshieee** [comment]
ストアからのインストール時は、正常に動作するため本件はクローズ致します。
